USE [master]
GO

/****** Object:  Database [vital1]    Script Date: 3/02/2021 4:01:33 p. m. ******/
CREATE DATABASE [vital1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vital1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\vital1.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'vital1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\vital1_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vital1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vital1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vital1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vital1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vital1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vital1] SET ARITHABORT OFF 
GO

ALTER DATABASE [vital1] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vital1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vital1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vital1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vital1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vital1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vital1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vital1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vital1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vital1] SET  ENABLE_BROKER 
GO

ALTER DATABASE [vital1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vital1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vital1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vital1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vital1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vital1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vital1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vital1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vital1] SET  MULTI_USER 
GO

ALTER DATABASE [vital1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vital1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vital1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vital1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [vital1] SET  READ_WRITE 
GO


USE [vital1]
GO

/****** Object:  Table [dbo].[Historial]    Script Date: 3/02/2021 4:02:29 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/******paso 2 Creacion tabla Producto ******/

USE [vital1]
GO

/****** Object:  Table [dbo].[Producto]    Script Date: 3/02/2021 4:03:54 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Producto](
	[Prod_Id] [int] IDENTITY(1,1) NOT NULL,
	[Prod_Desk] [varchar](255) NOT NULL,
	[Prod_Cant] [int] NOT NULL,
	[Prod_estado] [bit] NOT NULL,
 CONSTRAINT [PK__Persons__C55BDF136E714DCD] PRIMARY KEY CLUSTERED 
(
	[Prod_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



/******paso 3 Creacion tabla historico ******/

CREATE TABLE [dbo].[Historial](
	[Hist_ID] [int] IDENTITY(1,1) NOT NULL,
	[Hist_Cant] [int] NOT NULL,
	[Prod_Id] [int] NOT NULL,
	[Hist_Fecha] [datetime] NULL,
 CONSTRAINT [PK__Historia__16E101919C87F7DE] PRIMARY KEY CLUSTERED 
(
	[Hist_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Historial]  WITH CHECK ADD  CONSTRAINT [FK__Historial__Prod___1273C1CD] FOREIGN KEY([Prod_Id])
REFERENCES [dbo].[Producto] ([Prod_Id])
GO

ALTER TABLE [dbo].[Historial] CHECK CONSTRAINT [FK__Historial__Prod___1273C1CD]
GO


